### ISSUE TITLE
Consider running all tests under one run

### ISSUE THREAD

**Issue by kevmoo** [timsneath/time#1]
...generates a nice comparison output

```
#!/bin/bash

mkdir -p {dart,go,java}

dart2native hello.dart -o dart/hello 
go build -o go hello.go
javac -d java hello.java

hyperfine --warmup 3 --export-markdown 'results.md' \
  './hello.sh' \
  'go/hello' \
  'go run hello.go' \
  'dart/hello' \
  'dart hello.dart' \
  'java -cp java HelloWorld' \
  'node hello.js' \
  'python3 hello.py' \
  'ruby hello.rb'
```

| Command | Mean [ms] | Min [ms] | Max [ms] | Relative |
|:---|---:|---:|---:|---:|
| `./hello.sh` | 2.0 ± 0.5 | 0.7 | 3.9 | 1.00 |
| `go/hello` | 3.6 ± 0.4 | 2.4 | 5.5 | 1.81 ± 0.53 |
| `go run hello.go` | 299.2 ± 13.0 | 279.4 | 316.6 | 152.36 ± 42.48 |
| `dart/hello` | 10.3 ± 0.9 | 8.6 | 14.5 | 5.23 ± 1.52 |
| `dart hello.dart` | 600.9 ± 12.8 | 586.0 | 621.2 | 306.02 ± 84.53 |
| `java -cp java HelloWorld` | 107.7 ± 2.7 | 103.5 | 114.0 | 54.83 ± 15.16 |
| `node hello.js` | 70.4 ± 2.6 | 65.9 | 76.8 | 35.85 ± 9.96 |
| `python3 hello.py` | 32.3 ± 2.3 | 27.6 | 37.8 | 16.46 ± 4.68 |
| `ruby hello.rb` | 54.9 ± 3.0 | 51.0 | 66.1 | 27.98 ± 7.86 |

**Comment by timsneath** [comment]
Fixed with `https://github.com/timsneath/time/blob/master/compare.sh`
